import Navigate from "../components/navigator";
import "../styles/globals.css";

export const metadata = {
  title: {
    template: "%s | Movies",
    default: "loading",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Navigate />
        {children}
      </body>
    </html>
  );
}
